In [46]:
A = [[[1,2,3],[4,5,6], [7,8,9]], [[1,2,3],[4,5,6], [7,8,9]], [[1,2,3],[4,5,6], [7,8,9]]]
B = [[[1,2,3],[4,5,6], [7,8,9]], [[1,2,3],[4,5,6], [7,8,9]], [[1,2,3],[4,5,6], [7,8,9]]]
C = []

for i in range(len(A)):
    for j in range(len(A[i])):
        sec=[]
        for q in range(len(A[i][j])):
            sec.append(A[i][j][q] + B[i][j][q])
    C.append(sec)
        
for e in C:
    print(e)

[14, 16, 18]
[14, 16, 18]
[14, 16, 18]


In [60]:
n = int(input("Defina las filas"))
m = int(input("Defina las columnas"))
import random
A = []
B = []
C = []
valores = [1,2,3,4,5,6,7,8,9,0]

for e in range(n):
    sec = []
    for i in range(m):
        valor = random.choice(valores)
        sec.append(valor)
    A.append(sec)
print("Tu matriz A es:")
for e in A:
    print(e)

for e in range(n):
    sec = []
    for i in range(m):
        valor = random.choice(valores)
        sec.append(valor)
    B.append(sec)

print("Tu matriz B es:")
for e in B:
    print(e)
C = [[A[i][j] + B[i][j] for j in range(len(A[i]))] for i in range(len(A))]


print("\nLa suma es: ")
for e in C:
    print(e)

Tu matriz A es:
[1, 3, 2, 8]
[1, 2, 8, 0]
[9, 0, 2, 2]
Tu matriz B es:
[1, 8, 2, 9]
[4, 9, 9, 7]
[5, 8, 3, 5]

La suma es: 
[2, 11, 4, 17]
[5, 11, 17, 7]
[14, 8, 5, 7]


In [47]:
A = [[1,2,3],[4,5,6]]
B = [[4,5,6],[7,8,9]]
C = []

C = [[A[i][j] + B[i][j] for j in range(len(A[i]))] for i in range(len(A))]

print(C)

[[5, 7, 9], [11, 13, 15]]


In [71]:
cadena = "aA"
def contar_vocales(cadena):
    cadena = cadena.lower() 
    vocales = ["a","e","i","o","u"]
    dic = {key : 0 for key in vocales}
    for clave in dic:
        cant = 0
        for letra in cadena: 
            if letra == clave:
                dic[clave] += 1

    
    return dic



print(contar_vocales(cadena))
        

{'a': 2, 'e': 0, 'i': 0, 'o': 0, 'u': 0}


In [76]:
#NUMPY CON SLICING (numpy.padling)
#me devuelve la varianza y la media (vuelve 1 linea los 4 bloques)
import numpy as np

arrey = [[1,3],[5,8]]
pad_arr = np.pad(arrey, (2,2), 'mean') #con el mode mean, hizo la media

print(pad_arr)

[[4 4 3 6 4 4]
 [4 4 3 6 4 4]
 [2 2 1 3 2 2]
 [6 6 5 8 6 6]
 [4 4 3 6 4 4]
 [4 4 3 6 4 4]]
